Repository faberNovel/heart, pull requests merged in 2022-11, with the labels that each got.

#12 chore: adapt Gitlab CI to Github
  .github/workflows/pr.yaml
  .github/workflows/publish.yaml
  .gitlab-ci.yml
  CONTRIBUTING.md
  common/changes/@fabernovel/heart-core/chore-convert-ci-files-to-be-github-compatible_2022-11-15-09-36.json
Labels: ci/cd

#15 ci: add icons before steps and workflow names
  .github/workflows/pr.yaml
  .github/workflows/publish.yaml
Labels: ci/cd, developer experience

#5 [CLI] Show that the analysis are in progress by adding a spinner
  common/changes/@fabernovel/heart-api/126-cli-show-that-the-analysis-are-goin-on-by-adding-a-spinner_2022-10-22-21-06.json
  common/changes/@fabernovel/heart-cli/126-cli-show-that-the-analysis-are-goin-on-by-adding-a-spinner_2022-10-22-21-06.json
  common/changes/@fabernovel/heart-greenit/126-cli-show-that-the-analysis-are-goin-on-by-adding-a-spinner_2022-10-22-21-06.json
  common/config/rush/pnpm-lock.yaml
  modules/heart-api/src/ExpressApp.ts
  modules/heart-cli/package.json
  modules/heart-cli/src/App.ts
  modules/heart-cli/src/command/AnalysisCommand.ts
  modules/heart-cli/src/command/ServerCommand.ts
  modules/heart-cli/src/index.ts
  modules/heart-cli/tests/App.test.ts
  modules/heart-cli/tests/command/AnalysisCommand.test.ts
  modules/heart-cli/tests/command/ServerCommand.test.ts
  modules/heart-greenit/src/GreenITModule.ts
  modules/heart-greenit/src/api/Client.ts
  modules/heart-greenit/tests/GreenITModule.test.ts
Labels: enhancement

#2 [Lighthouse] Upgrade the lighthouse dependency
  common/changes/@fabernovel/heart-lighthouse/125-lighthouse-upgrade-the-ligthouse-dependency_2022-10-23-21-49.json
  common/config/rush/pnpm-lock.yaml
  modules/heart-lighthouse/package.json
  modules/heart-lighthouse/src/@types/lighthouse/index.d.ts
  modules/heart-lighthouse/src/@types/lighthouse/lighthouse-core/index.d.ts
  modules/heart-lighthouse/src/LighthouseModule.ts
  modules/heart-lighthouse/src/api/Client.ts
  modules/heart-lighthouse/src/config/Config.ts
  modules/heart-lighthouse/src/scoring/compute.ts
  modules/heart-lighthouse/tests/LighthouseModule.test.ts
  modules/heart-lighthouse/tests/api/Client.test.ts
  modules/heart-lighthouse/tsconfig.json
Labels: enhancement

#17 [BigQuery] Module does not work ‼️
  common/changes/@fabernovel/heart-bigquery/fix-bigquery-threshold_2022-11-21-21-35.json
  common/changes/@fabernovel/heart-greenit/fix-bigquery-threshold_2022-11-21-21-35.json
  modules/heart-bigquery/src/BigQueryModule.ts
  modules/heart-bigquery/src/api/BigQuery/Client.ts
  modules/heart-bigquery/src/api/BigQuery/Definitions.ts
  modules/heart-greenit/src/GreenITModule.ts
  modules/heart-greenit/src/api/model/Result.ts
  modules/heart-greenit/tests/GreenITModule.test.ts
  modules/heart-greenit/tests/data/successReport.json
Labels: bug

#21 ci: fix syntax
  .github/workflows/publish.yaml
Labels: bug, ci/cd

#22 ci: improve genericity of the PR worflow and fix jobs names with injected variable
  .github/workflows/pr.yaml
  .github/workflows/publish.yaml
Labels: bug, ci/cd

#29 Guess node version
  .github/workflows/pr.yaml
  .github/workflows/publish.yaml
  rush.json
Labels: enhancement, ci/cd

#23 Change the publication strategy
  .github/CODEOWNERS
  .github/workflows/publish.yaml
Labels: ci/cd

#32 ci: fix missing installation step
  .github/workflows/publish.yaml
Labels: bug, ci/cd

#33 ci: fix missing build step for publish mode
  .github/workflows/publish.yaml
Labels: bug, ci/cd

#35 ci: remove useless condition
  .github/workflows/publish.yaml
Labels: bug, ci/cd

#36 ci: fix missing environment variable NPM_TOKEN
  .github/workflows/publish.yaml
Labels: bug, ci/cd

#39 fix: lock file
  common/config/rush/pnpm-lock.yaml
Labels: bug

#38 ci: add explaination and improve workflow options names
  .github/workflows/publish.yaml
Labels: documentation, ci/cd, developer experience

#41 chore: remove old ignore directories
  .gitignore
Labels: enhancement

#45 fix: use GitHub URLs for icons, and update the one of the GreenIT module
  assets/images/logos/GreenIT.png
  assets/images/logos/ecoIndex.png
  common/changes/@fabernovel/heart-bigquery/fix-greenit-logo_2022-11-26-13-58.json
  common/changes/@fabernovel/heart-dareboost/fix-greenit-logo_2022-11-26-13-58.json
  common/changes/@fabernovel/heart-greenit/fix-greenit-logo_2022-11-26-13-58.json
  common/changes/@fabernovel/heart-lighthouse/fix-greenit-logo_2022-11-26-13-58.json
  common/changes/@fabernovel/heart-observatory/fix-greenit-logo_2022-11-26-13-58.json
  common/changes/@fabernovel/heart-slack/fix-greenit-logo_2022-11-26-13-58.json
  common/changes/@fabernovel/heart-ssllabs-server/fix-greenit-logo_2022-11-26-13-58.json
  modules/heart-bigquery/src/index.ts
  modules/heart-dareboost/src/index.ts
  modules/heart-greenit/src/index.ts
  modules/heart-lighthouse/src/index.ts
  modules/heart-observatory/src/index.ts
  modules/heart-slack/src/index.ts
  modules/heart-ssllabs-server/src/index.ts
Labels: bug

#46 docs: add a changelog about the logo change
  common/changes/@fabernovel/heart-greenit/fix-greenit-logo_2022-11-26-13-58.json
Labels: documentation

#47 Update lock file after publication
  .github/workflows/publish.yaml
  rush.json
Labels: bug, ci/cd

#49 Update GitLab references
  CONTRIBUTING.md
  README.md
  common/changes/@fabernovel/heart-api/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-bigquery/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-cli/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-core/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-dareboost/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-greenit/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-lighthouse/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-observatory/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-slack/docs-update-gitlab-references_2022-11-27-11-09.json
  common/changes/@fabernovel/heart-ssllabs-server/docs-update-gitlab-references_2022-11-27-11-09.json
  modules/heart-api/package.json
  modules/heart-bigquery/package.json
  modules/heart-cli/package.json
  modules/heart-core/package.json
  modules/heart-dareboost/package.json
  modules/heart-greenit/package.json
  modules/heart-lighthouse/package.json
  modules/heart-observatory/package.json
  modules/heart-slack/package.json
  modules/heart-ssllabs-server/package.json
Labels: documentation

#54 ci: remove old condition
  .github/workflows/publish.yaml
Labels: bug, ci/cd
